# Generated by Django 4.1 on 2022-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', verbose_name='변환 전 텍스트')),
                ('speed', models.FloatField(choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0)], default=1.0, verbose_name='오디오 속도')),
                ('audio_id', models.PositiveIntegerField(default=0, verbose_name='오디오 식별자')),
            ],
        ),
    ]
