# Generated by Django 4.1 on 2022-09-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
