# Generated by Django 4.1 on 2022-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('project_id', models.IntegerField(unique=True)),
                ('project_title', models.CharField(max_length=100, verbose_name='프로젝트 이름')),
            ],
        ),
    ]
