# Generated by Django 4.1 on 2022-09-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(unique=True)),
                ('project_title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
